parameters:
    app_engine.default_database_dsn: mysql:unix_socket=%database_unix_socket%;dbname=%database_name%

services:
    pdo:
        class: PDO
        arguments: [ %app_engine.default_database_dsn%, %database_user%, %database_password% ]
