parameters:
    app_engine.default_database_dsn: %default_database_dsn%

services:
    pdo:
        class: PDO
        arguments: [ %app_engine.default_database_dsn%, %database_user%, %database_password% ]
