parameters:
    app_engine.provider.user.class: Caxy\AppEngine\Bridge\Security\User\AppEngineUserProvider
    app_engine.security.authentication.provider.class: Caxy\AppEngine\Bridge\Security\Authentication\AppEngineAuthenticationProvider
    app_engine.security.authentication.listener.class: Caxy\AppEngine\Bridge\Security\Firewall\AppEngineAuthenticationListener
    app_engine.user.class: Caxy\AppEngine\Bridge\Security\User\User

services:
    app_engine.provider.user:
        class: %app_engine.provider.user.class%

    app_engine.security.authentication.provider:
        class: %app_engine.security.authentication.provider.class%
        arguments: [~]

    app_engine.security.authentication.listener:
        class: %app_engine.security.authentication.listener.class%
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        abstract: true
