parameters:
    app_engine.provider.user.class: Caxy\AppEngine\Bridge\Security\User\UserProvider
    app_engine.user.class: Caxy\AppEngine\Bridge\Security\User\User

services:
    app_engine.provider.user:
        class: %app_engine.provider.user.class%

    app_engine.security.authentication.provider:
        class: FOS\UserBundle\Security\UserProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    app_engine.security.authentication.listener:
        class: Caxy\AppEngine\Bundle\Security\Firewall\Listener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
