parameters:
    app_engine.provider.user.class: Caxy\AppEngine\Bridge\Security\User\UserProvider
    app_engine.provider.authentication.class: Caxy\AppEngine\Bridge\Security\Authentication\Provider
    app_engine.listener.authentication.class: Caxy\AppEngine\Bridge\Security\Firewall\Listener
    app_engine.user.class: Caxy\AppEngine\Bridge\Security\User\User

services:
    app_engine.security.authentication.provider:
        class: %app_engine.provider.authentication.class%
        arguments: [""]

    app_engine.security.authentication.listener:
        class: %app_engine.listener.authentication.class%
        arguments: ["@security.token_storage", "@security.authentication.manager"]
